services:
  # MinIO
  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network
    restart: unless-stopped

  minio_setup:
    image: minio/mc:latest
    container_name: minio_setup
    profiles: ["setup"]
    depends_on:
      minio:
        condition: service_started
    networks:
      - app_network
    volumes:
      - ./projects/ops/minio-setup/init.sh:/init.sh:ro
      - ./projects/ops/minio-setup/setup-uploads.sh:/setup-uploads.sh:ro
     # - ./projects/ops/minio-setup/setup-backups.sh:/setup-backups.sh:ro
    entrypoint: ['/bin/sh','-c','sh /init.sh']
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_APP_ACCESS_KEY: ${MINIO_APP_ACCESS_KEY}
      MINIO_APP_SECRET_KEY: ${MINIO_APP_SECRET_KEY}
      # MINIO_BACKUP_ACCESS_KEY: ${MINIO_BACKUP_ACCESS_KEY}
      # MINIO_BACKUP_SECRET_KEY: ${MINIO_BACKUP_SECRET_KEY}
    restart: 'no'

  # PostgreSQL
  postgres:
    image: postgres:16.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    restart: unless-stopped

  # NestJS сервер
  server:
    build:
      context: .
      dockerfile: projects/server/Dockerfile.dev
    container_name: server
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      S3_PUBLIC_BASE_URL: ${S3_PUBLIC_BASE_URL}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_UPLOADS: ${S3_BUCKET_UPLOADS}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./projects/server:/server/projects/server
      - ./packages:/server/packages
      - ./package.json:/server/package.json:ro
      - ./pnpm-lock.yaml:/server/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/server/pnpm-workspace.yaml
      - ./projects/server/node_modules:/server/projects/server/node_modules
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:3000/api/ >/dev/null 2>&1 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 100s
    restart: unless-stopped

  # React клиент
  client:
    build:
      context: .
      dockerfile: projects/client/Dockerfile.dev
    container_name: client
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost/api}
    volumes:
      - ./projects/client:/client/projects/client
      - ./packages:/client/packages
      - ./package.json:/client/package.json:ro
      - ./pnpm-lock.yaml:/client/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/client/pnpm-workspace.yaml
      - ./projects/client/node_modules:/client/projects/client/node_modules
    ports:
      - '5173:5173'
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:5173/ >/dev/null 2>&1 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Nginx
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./projects/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./projects/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - app_network
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
networks:
  app_network:
    driver: bridge
