services:
  # PostgreSQL
  postgres:
    image: postgres:16.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    restart: unless-stopped

  # NestJS сервер
  server:
    build:
      context: .
      dockerfile: projects/server/Dockerfile.dev
    container_name: server
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL:-postgresql://user:password@postgres:5432/db}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3000}
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./projects/server:/server/projects/server
      - ./package.json:/server/package.json:ro
      - ./pnpm-lock.yaml:/server/pnpm-lock.yaml:ro
      - ./pnpm-workspace.yaml:/server/pnpm-workspace.yaml:ro
      - ./projects/server/node_modules:/server/projects/server/node_modules
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:3000/api/ >/dev/null 2>&1 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped

  # React клиент
  client:
    build:
      context: .
      dockerfile: projects/client/Dockerfile.dev
    container_name: client
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost/api}
    volumes:
      - ./projects/client:/client/projects/client
      - ./packages:/client/packages
      - ./package.json:/client/package.json:ro
      - ./pnpm-lock.yaml:/client/pnpm-lock.yaml:ro
      - ./pnpm-workspace.yaml:/client/pnpm-workspace.yaml:ro
      - ./projects/client/node_modules:/client/projects/client/node_modules
    ports:
      - '5173:5173'
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:5173/ >/dev/null 2>&1 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Nginx
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./projects/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./projects/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge
