name: CI

on:
  push:
    branches: ["development"]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to \'main\' branch
      uses: actions/checkout@v5

    - name: Check secrets presence
      env:
        ALL_SECRETS_JSON: ${{ toJSON(secrets) }}
      run: ./scripts/check-secrets.sh

    - name: Node setup
      uses: actions/setup-node@v6
      with:
        node-version: 20

    - name: Install pnpm and dependencies
      uses: pnpm/action-setup@v4
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      with:
        run_install: true
        args: --frozen-lockfile 

    - name: Generate Prisma Client
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pnpm --filter @lemnity/database exec prisma generate
  
    - name: Lint
      run: pnpm --filter client --filter server lint

    - name: Format
      run: pnpm --filter client --filter server format

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build server image
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
        S3_PUBLIC_BASE_URL: ${{ secrets.S3_PUBLIC_BASE_URL }}
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_REGION: ${{ secrets.S3_REGION }}
        S3_BUCKET_UPLOADS: ${{ secrets.S3_BUCKET_UPLOADS }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/server:${{ github.sha }} \
          -f projects/server/Dockerfile .
    
    - name: Build client image
      env:
        API_URL: ${{ secrets.API_URL }}
        NODE_ENV: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/client:${{ github.sha }} \
          -f projects/client/Dockerfile .

    - name: Push images
      run: |
        docker push ghcr.io/${{ github.repository }}/server:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/client:${{ github.sha }}

    - name: Save tag for CD
      id: save_tag
      run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
