name: CI

on:
  push:
    branches: ["development"]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to \'main\' branch
      uses: actions/checkout@v5

    - name: Check secrets presence
      env:
        ALL_SECRETS_JSON: ${{ toJSON(secrets) }}
      run: ./scripts/check-secrets.sh

    - name: Node setup
      uses: actions/setup-node@v6
      with:
        node-version: latest

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pnpm install --frozen-lockfile

    - name: Lint
      run: pnpm --filter client --filter server lint

    - name: Format
      run: pnpm --filter client --filter server format

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build server image
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/server:${{ github.sha }} \
          -f projects/server/Dockerfile .
    
    - name: Build client image
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/client:${{ github.sha }} \
          -f projects/client/Dockerfile .

    - name: Push images
      run: |
        docker push ghcr.io/${{ github.repository }}/server:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/client:${{ github.sha }}

    - name: Save tag for CD
      id: save_tag
      run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
